version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=https://svjpdlkwyboljjtvqivc.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2anBkbGt3eWJvbGpqdHZxaXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDg1NTksImV4cCI6MjA1Nzg4NDU1OX0.P9tShtVo9hnuKVE2IycZ5QkVWiZuPsBR5El1YXnq-D4

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=https://svjpdlkwyboljjtvqivc.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2anBkbGt3eWJvbGpqdHZxaXZjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjMwODU1OSwiZXhwIjoyMDU3ODg0NTU5fQ.AxyWIRGCP8kh05NrkszntDxbSyB6uRfMsH80YM1b8kg
