apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bounty-secret-provider
  namespace: bounty-app
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/bounty-458107/secrets/supabase-url/versions/latest" 
        fileName: "supabase-url" 
      - resourceName: "projects/bounty-458107/secrets/supabase-key/versions/latest"
      - resourceName: "projects/bounty-458107/secrets/jwt-secret/versions/latest" 
        fileName: "jwt-secret"
  
  secretObjects:
  - secretName: bounty-secrets-env # Name of the K8s secret to create/update
    type: Opaque
    data:
      - key: supabase-url # Key name within the K8s secret
        objectName: supabase-url # Matches fileName above
      - key: supabase-key
        objectName: supabase-key
      - key: jwt-secret
        objectName: jwt-secret