# k8s/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bounty-ksa # The name referenced in the deployment
  namespace: bounty-app # Must be in the same namespace as the deployment
  annotations:
    # This annotation links the KSA to the GSA via WIF
    iam.gke.io/gcp-service-account: github-actions-cicd@bounty-458107.iam.gserviceaccount.com # <<<--- REPLACE with your GSA email